# Generated by Django 5.2.10 on 2026-01-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stagione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadra', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('girone', models.CharField(max_length=5)),
                ('posizione', models.PositiveSmallIntegerField()),
                ('stagione', models.CharField(max_length=20)),
                ('inizio', models.DateField()),
                ('fine', models.DateField()),
                ('partite_giocate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('casa', models.CharField(max_length=100)),
                ('trasferta', models.CharField(max_length=100)),
                ('gol_casa', models.PositiveIntegerField()),
                ('gol_trasferta', models.PositiveIntegerField()),
                ('campo', models.CharField(choices=[('casa', 'Casa'), ('trasferta', 'Trasferta')], max_length=10)),
                ('risultato', models.CharField(choices=[('V', 'Vittoria'), ('P', 'Perdita'), ('N', 'Pareggio')], max_length=1)),
                ('stagione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite', to='campionato.stagione')),
            ],
        ),
    ]
